---
controller_execution_environments:
  - name: "CaC Execution Environment"
    description: ""
    organization: "MobileLab"
    image: "hub.mobile.bk.lab/config_ee"
    pull: "missing"
    credential: "Automation Hub Container Registry"
  - name: "Automation Hub Minimal execution environment"
    description: ""
    image: "hub.mobile.bk.lab/ee-minimal-rhel8:latest"
    pull: ""
    credential: "Automation Hub Container Registry"
  - name: "Automation Hub Default execution environment"
    description: ""
    image: "hub.mobile.bk.lab/ee-supported-rhel8:latest"
    pull: ""
    credential: "Automation Hub Container Registry"
  - name: "Control Plane Execution Environment"
    description: ""
    image: "hub.mobile.bk.lab/ee-supported-rhel8:latest"
    pull: ""
    credential: "Automation Hub Container Registry"
...
