---
controller_settings:
  - settings:
      TOWER_URL_BASE: "https://controller.mobile.bk.lab"
      LICENSE:
        account_number: '6265693'
        instance_count: 10
        license_date: '1720324799'
        license_type: enterprise
        pool_id: 2c94cdce890c6dae01892728e0c36b66
        product_name: Employee SKU
        satellite: false
        sku: ES0113909
        subscription_id: '13189332'
        subscription_name: Employee SKU
        support_level: Self-Support
        trial: false
        usage: Development/Test
        valid_key: true
      INSTALL_UUID: "d1a59779-1ce4-4cf6-a3e1-a44e6e965520"
...
