---
- name: Create initial filetree for Automation Controller CaC
  hosts: utility
  become: false
  gather_facts: false
  vars_files:
    - vault.yml
  pre_tasks:
    - name: Setup authentication (block)
      when: controller_oauthtoken is not defined
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      tags:
        - always
      block:
        - name: Get the Auth Token for future requests
          ansible.builtin.uri:
            url: "https://{{ controller_hostname }}/api/v2/tokens/"
            user: "{{ controller_username }}"
            password: "{{ controller_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ controller_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: Set the oauth token to be used since now
          ansible.builtin.set_fact:
            controller_oauthtoken: "{{ authtoken_res.json.token }}"
            controller_oauthtoken_url: "{{ authtoken_res.json.url }}"

  roles:
    - infra.controller_configuration.filetree_create

  post_tasks:
    - name: Delete the Auth Token
      ansible.builtin.uri:
        url: "https://{{ controller_hostname }}{{ controller_oauthtoken_url }}"
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ controller_validate_certs }}"
        status_code: 204
      when: controller_oauthtoken_url is defined
...
