all:
  children:
    aap:
      children:
        aapdb:
          hosts:
            postgresql.bk.lab:
        automationhub:
          hosts:
            automationhub.bk.lab:
        controller:
          hosts:
            controller.bk.lab:
        eda:
          hosts:
           edacontroller.bk.lab:
        execution:
          hosts:
            execution01.bk.lab:
            execution02.bk.lab:
    utility:
      hosts:
        utility.bk.lab:
    managed:
      hosts:
        node01.bk.lab:
        node02.bk.lab:
        node03.bk.lab:
    labhost:
      hosts:
        lab.bk.local:
    ungrouped: {}
