all:
  children:
    aap:
      children:
        aapdb:
          hosts:
            postgres.bk.lab:
        automationhub:
          hosts:
            hub.bk.lab:
        controller:
          hosts:
            controller.bk.lab:
#        edaserver:
#          hosts:
#           eda.bk.lab:
        execution:
          hosts:
            execution01.bk.lab:
            execution02.bk.lab:
    utility:
      hosts:
        utility.bk.lab:
    labhost:
      hosts:
        lab.bk.local:
    ungrouped: {}
