---
controller_projects:
  - name: "AAP Configuration as Code"
    description: ""
    organization: "MobileLab"
    scm_type: "git"
    scm_url: "https://github.com/bpkrumme/aap_config_as_code.git"
    scm_branch: ""
    scm_clean: "True"
    scm_delete_on_update: "False"
    scm_update_on_launch: "False"
    scm_update_cache_timeout: "0"
    allow_override: "False"
    timeout: 0
...
