---
controller_credentials:
  - name: "Default Execution Environment Registry Credential"
    description: ""
    credential_type: "Container Registry"
    organization: "ORGANIZATIONLESS"
    inputs:
      host: registry.redhat.io
      password: ''
      username: 5034321|redhatio
      verify_ssl: true

...
